#===============================================================================
#
# Look at 003_Variables Switches Alias.rb file to know how to use this class.
#
# When updating the script to a new version, don't update this file, so you can
# keep the variables that you already inserted.
#
#===============================================================================

# Insert here your switch keys to switch numbers, using the pattern.
$gs = SwitchesAlias.new({
  :STARTING_OVER                 => 1  ,
  :SEEN_POKERUS                  => 2  ,
  :SEEN_POKERUS_IN_POKECENTER    => 2  ,
  :STARTER                       => 3  ,
  :CHOSE_STARTER                 => 3  ,
  :CHOOSING_STARTER              => 3  ,
  :GYM1                          => 4  ,
  :DEFEATED_GYM_1                => 4  ,
  :GYM2                          => 5  ,
  :DEFEATED_GYM_2                => 5  ,
  :GYM3                          => 6  ,
  :DEFEATED_GYM_3                => 6  ,
  :GYM4                          => 7  ,
  :DEFEATED_GYM_4                => 7  ,
  :GYM5                          => 8  ,
  :DEFEATED_GYM_5                => 8  ,
  :GYM6                          => 9  ,
  :DEFEATED_GYM_6                => 9  ,
  :GYM7                          => 10 ,
  :DEFEATED_GYM_7                => 10 ,
  :GYM8                          => 11 ,
  :DEFEATED_GYM_8                => 11 ,
  :E4                            => 12 ,
  :DEFEATED_ELITE_FOUR           => 12 ,
  :FOSSIL_REVIVING               => 13 ,
  :FOSSIL_REVIVAL_IN_PROGRESS    => 13 ,
  :NATIONAL_DEX                  => 29 ,
  :HAS_NATIONAL_DEX              => 29 ,
  :SHINY_WILD                    => 31 ,
  :SHINY_WILD_PKMN               => 31 ,
  :SHINY_WILD_POKEMON            => 31 ,
  :FATEFUL_ENCOUNTERS            => 32 ,
  :NO_MONEY_LOST                 => 33 ,
  :NO_MONEY_LOST_IN_BATTLES      => 33 ,
  :NO_MEGA                       => 34 ,
  :NO_MEGA_EVOLUTION             => 34 ,
  :NO_LINK_BOX                   => 35 ,
  :DISABLE_LINK_BOX              => 35 ,
  :BERTH_ISLAND                  => 51 ,
  :VISITED_BERTH_ISLAND          => 51 ,
  :FARADAY_ISLAND                => 52 ,
  :VISITED_FARADAY_ISLAND        => 52 ,
  :LATIES_ROAMING                => 53 ,
  :LATIXS_ROAMING                => 53 ,
  :LATIAS_LATIOS_ROAMING         => 53 ,
  :KYOGRE_ROAMING                => 54 ,
  :ENTEI_ROAMING                 => 55 ,
  :RESET_MEW                     => 56 ,
  :RESET_MEW_ENCOUNTER           => 56 ,
  :BOULDER_DOWN_ROCK_CAVE        => 57 ,
  :BOULDER_DOWN_HOLE_ROCK_CAVE   => 57 ,
  :BOULDER_DOWN_ICE_CAVE         => 58 ,
  :BOULDER_DOWN_HOLE_ICEK_CAVE   => 58 ,
},true)

# Insert here your variable keys to variable numbers, using the pattern.
$gv = VariablesAlias.new({
  :TEMP_PKMN                     => 1  ,
  :TEMP_PKMN_CHOICE              => 1  ,
  :TEMP_POKEMON                  => 1  ,
  :TEMP_POKEMON_CHOICE           => 1  ,
  :TEMP_MOVE                     => 2  ,
  :TEMP_MOVE_CHOICE              => 2  ,
  :TEMP_PKMN_NAME                => 3  ,
  :TEMP_POKEMON_NAME             => 3  ,
  :TEMP_MOVE_NAME                => 4  ,
  :TEMP_TEXT                     => 5  ,
  :TEMP_TEXT_ENTRY               => 5  ,
  :POKECENTER_BALLS              => 6  ,
  :POKECENTER_BALL_COUNT         => 6  ,
  :POKECENTER_HEALING_BALL_COUNT => 6  ,
  :STARTER                       => 7  ,
  :STARTER_CHOICE                => 7  ,
  :APRICORN_DELIVERED            => 8  ,
  :FOSSIL_DELIVERED              => 9  ,
  :ELEVATOR_CURRENT              => 10 ,
  :ELEVATOR_CURRENT_FLOOR        => 10 ,
  :ELEVATOR_NEW                  => 11 ,
  :ELEVATOR_NEW_FLOOR            => 11 ,
  :RIVAL_NAME                    => 12 ,
  :E4_DEFEAT                     => 13 ,
  :E4_DEFEAT_COUNT               => 14 ,
  :FOSSIL_SPECIES                => 15 ,
  :COMBINED_FOSSIL_SPECIES       => 15 ,
},true)